/* production.h
 *  Created on: 2013-4-8
 *      Author: y
 */
#ifndef PRODUCTION_H_
#define PRODUCTION_H_



#define PRODUCTION_LEFT_SIZE 32
#define PRODUCTION_RIGHT_SIZE 128



#define E	222 // ERROR
#define N	999
#define AC	0



typedef struct{
	int left;
	char right[PRODUCTION_RIGHT_SIZE];
	int right_count;
}PRODUCTION;



char * production_left[] = {
		"_start",
		"start",
		"main_func",
		"func",
		"func_content",
		"func_list",
		"ret_smt",
		"param_list",
		"param_item",
		"t_type",
		"ret_type",
		"type",
		"array",
		"declare",
		"exp",
		"exp_item",
		"term",
		"factor",
		"addop",
		"mulop",
		"relop",
		"bolop",
		"smt_list",
		"smt",
		"call_func",
		"bool_exp",
		"bool_exp_item",
		"if_smt",
		"if_content",
};

/*
 * production_left\[(\d+\+?\d?)\],"([(\w*\s?)(,)]+)",(\d)
 * \1],"\2",\3,\1
 */




PRODUCTION production[] = {
		{0,"",0},
		{0,"start",1},
		{1,"main_func func_list",2},
		{1,"main_func",1},
		{2,"void main func_content",3},
		{7,", param_list",2},
		{7,"param_item",1},
		{8,"t_type id",2},
		{9,"array",1},
		{9,"type",1},
		{11,"float",1},
		{11,"bool",1},
		{11,"char",1},
		{11,"int",1},
		{11,"string",1},
		{12,"type [ num ]",4},
		{3,"ret_type id func_content",3},
		{4,"( ) { smt_list ; }",6},
		{4,"( param_list ) { smt_list ;}",7},
		{10,"void",1},
		{10,"type",1},
		{6,"return num",2},
		{6,"return id",2},
		{6,"return",1},
		{5,"func func_list",2},
		{5,"func",1},
		{13,"t_type id",2},
		{18,"-",1},
		{18,"+",1},
		{19,"/",1},
		{19,"*",1},
		{20,">=",1},
		{20,"<=",1},
		{20,"<>",1},
		{20,">",1},
		{20,"<",1},
		{20,"==",1},
		{21,"||",1},
		{21,"&&",1},
		{24,"id(param_list)",4},
		{24,"id = id ( param_list )",6},
		{24,"id=id()",5},
		{24,"id()",3},
		{14,"call_func",1},
		{14,"id=exp_item",3},
		{15,"term",1},
		{15,"exp_item addop term",3},
		{16,"term mulop factor",3},
		{16,"factor",1},
		{17,"num",1},
		{17,"(exp_item)",3},
		{17,"id",1},
		{22,"smt_list ; smt",3},
		{22,"smt",1},
		{23,"while ( bool_exp ) { smt_list ; }",8},
		{23,"if_smt",1},
		{23,"continue",1},
		{23,"break",1},
		{23,"ret_smt",1},
		{23,"exp",1},
		{23,"declare",1},
		{27,"if_content else { smt_list ; }",6},
		{27,"if_content",1},
		{28,"if(bool_exp){smt_list;}",8},
		{25,"bool_exp_item bolop bool_exp",3},
		{25,"bool_exp_item",1},
		{26,"exp_item relop exp_item",3},
		{26,"exp_item",1},
};
int action[][37] = {
		{E,-3,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{AC,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{3,-8,E,E,E,E,E,E,E,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,-14,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{25,-8,E,E,E,E,E,E,E,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{2,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,-16,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,19,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,19,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,13,E,E,E,E,E,13,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,12,E,E,E,E,E,12,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,11,E,E,E,E,E,11,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,10,E,E,E,E,E,10,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,14,E,E,E,E,E,14,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-18,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{24,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-18,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{4,4,E,E,E,E,E,E,E,4,4,4,4,4,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,-25,E,E,-26,E,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{16,16,E,E,E,E,E,E,E,16,16,16,16,16,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,-27,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,6,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,-28,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,9,E,E,E,E,E,-29,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,8,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,-30,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,-26,E,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,-32,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,7,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,-33,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,-43,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,-44,-45,E,E,E,E,E,E,E,E,E,-46,-47,-48},
		{E,E,E,E,5,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,-43,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,-44,-45,E,E,E,E,E,E,E,E,E,-46,-47,-48},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,-50,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,58,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,-51,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,60,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,59,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,-52,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,53,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,43,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,55,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,62,E,E,E,E,E,E,E,-53,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-54,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,-55,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-56,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-57,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,-58,E,E,E,E,E,E,E,-59,23,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,57,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,56,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,-60,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,15,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,26,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,-62,E,-43,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,-44,-45,E,E,E,E,E,E,E,E,E,-46,-47,-48},
		{E,E,E,E,E,-63,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,-65,E,E,-26,E,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-69,E,E,E,E,-70,E,E,E,E,E,E,E,-71,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-69,E,E,E,E,-75,E,E,E,E,E,E,E,-71,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-69,E,E,E,E,-75,E,E,E,E,E,E,E,-71,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,22,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,21,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,-77,E,-43,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,-44,-45,E,E,E,E,E,E,E,E,E,-46,-47,-48},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,52,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{17,17,E,E,E,E,E,E,E,17,17,17,17,17,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,-43,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,-44,-45,E,E,E,E,E,E,E,E,E,-46,-47,-48},
		{E,E,E,E,-79,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,42,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,44,-81,-82,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,45,E,E,E,E,E,E,E,E,E,E,E,E,45,45,45,-84,-85,E,E,E,E,45,45,45,45,45,45,45,45,E,E,E},
		{E,E,E,E,48,E,E,E,E,E,E,E,E,E,E,E,E,48,48,48,48,48,E,E,E,E,48,48,48,48,48,48,48,48,E,E,E},
		{E,E,E,-69,E,E,E,E,-75,E,E,E,E,E,E,E,-71,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-87,E,E,E,E,E,E,E,E,E,E,E,E,E,51,51,51,51,51,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,49,E,E,E,E,E,E,E,E,E,E,E,E,49,49,49,49,49,E,E,E,E,49,49,49,49,49,49,49,49,E,E,E},
		{E,E,E,E,67,E,E,E,E,E,E,E,E,E,E,E,E,E,-81,-82,E,E,E,E,E,E,-89,-90,-91,-92,-93,-94,67,67,E,E,E},
		{E,E,E,E,-95,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,65,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,-97,-98,E,E,E},
		{E,E,E,E,51,E,E,E,E,E,E,E,E,E,E,E,E,51,51,51,51,51,E,E,E,E,51,51,51,51,51,51,51,51,E,E,E},
		{E,E,E,E,-99,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{18,18,E,E,E,E,E,E,E,18,18,18,18,18,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,-100,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,39,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-69,E,E,E,E,-75,E,E,E,E,E,E,E,-71,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,28,E,E,E,E,28,E,E,E,E,E,E,E,28,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,27,E,E,E,E,27,E,E,E,E,E,E,E,27,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-69,E,E,E,E,-75,E,E,E,E,E,E,E,-71,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,30,E,E,E,E,30,E,E,E,E,E,E,E,30,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,29,E,E,E,E,29,E,E,E,E,E,E,E,29,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,-103,E,E,E,E,E,E,E,E,E,E,E,E,E,-81,-82,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,-105,E,E,-26,E,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-69,E,E,E,E,-75,E,E,E,E,E,E,E,-71,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,34,E,E,E,E,34,E,E,E,E,E,E,E,34,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,35,E,E,E,E,35,E,E,E,E,E,E,E,35,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,31,E,E,E,E,31,E,E,E,E,E,E,E,31,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,32,E,E,E,E,32,E,E,E,E,E,E,E,32,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,33,E,E,E,E,33,E,E,E,E,E,E,E,33,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,36,E,E,E,E,36,E,E,E,E,E,E,E,36,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,-107,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,-69,E,E,E,E,-75,E,E,E,E,E,E,E,-71,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,37,E,E,E,E,37,E,E,E,E,E,E,E,37,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,38,E,E,E,E,38,E,E,E,E,E,E,E,38,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,-109,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,-110,E,-43,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,-44,-45,E,E,E,E,E,E,E,E,E,-46,-47,-48},
		{E,E,E,E,46,E,E,E,E,E,E,E,E,E,E,E,E,46,46,46,-84,-85,E,E,E,E,46,46,46,46,46,46,46,46,E,E,E},
		{E,E,E,E,47,E,E,E,E,E,E,E,E,E,E,E,E,47,47,47,47,47,E,E,E,E,47,47,47,47,47,47,47,47,E,E,E},
		{E,E,E,E,50,E,E,E,E,E,E,E,E,E,E,E,E,50,50,50,50,50,E,E,E,E,50,50,50,50,50,50,50,50,E,E,E},
		{E,E,E,E,-111,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,41,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,66,E,E,E,E,E,E,E,E,E,E,E,E,E,-81,-82,E,E,E,E,E,E,E,E,E,E,E,E,66,66,E,E,E},
		{E,E,E,E,E,E,E,E,-43,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,-44,-45,E,E,E,E,E,E,E,E,E,-46,-47,-48},
		{E,E,E,E,64,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,-43,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,-44,-45,E,E,E,E,E,E,E,E,E,-46,-47,-48},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,61,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,40,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,-114,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,-115,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,-116,E,-43,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,-44,-45,E,E,E,E,E,E,E,E,E,-46,-47,-48},
		{E,E,E,E,E,E,-117,E,-43,-9,-10,-11,-12,-13,E,E,E,E,E,E,E,E,E,-44,-45,E,E,E,E,E,E,E,E,E,-46,-47,-48},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,63,E,E,E,E,E,E,E,63,E,E,E,E,E,E,E,E,E,E,E},
		{E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,54,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
};

int go_to[][29] = {
		{N,1,2,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,4,E,5,E,E,E,E,6,7,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,4,E,15,E,E,E,E,6,7,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,17,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,19,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,20,21,22,E,23,24,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,31,21,22,E,23,24,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,34,E,E,35,E,23,24,36,37,E,E,E,E,E,E,E,38,39,40,E,E,41,42},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,34,E,E,35,E,23,24,36,37,E,E,E,E,E,E,E,49,39,40,E,E,41,42},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,34,E,E,35,E,23,24,36,37,E,E,E,E,E,E,E,E,61,40,E,E,41,42},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,64,21,22,E,23,24,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,66,67,68,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,72,67,68,E,E,E,E,E,E,E,73,74,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,72,67,68,E,E,E,E,E,E,E,76,74,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,34,E,E,35,E,23,24,36,37,E,E,E,E,E,E,E,E,61,40,E,E,41,42},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,34,E,E,35,E,23,24,36,37,E,E,E,E,E,E,E,78,39,40,E,E,41,42},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,80,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,83,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,86,67,68,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,80,E,88,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,96,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,101,68,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,102,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,80,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,104,21,22,E,23,24,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,106,67,68,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,72,67,68,E,E,E,E,E,E,E,108,74,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,34,E,E,35,E,23,24,36,37,E,E,E,E,E,E,E,E,61,40,E,E,41,42},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,83,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,80,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,34,E,E,35,E,23,24,36,37,E,E,E,E,E,E,E,112,39,40,E,E,41,42},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,34,E,E,35,E,23,24,36,37,E,E,E,E,E,E,E,113,39,40,E,E,41,42},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,34,E,E,35,E,23,24,36,37,E,E,E,E,E,E,E,E,61,40,E,E,41,42},
		{N,E,E,E,E,E,34,E,E,35,E,23,24,36,37,E,E,E,E,E,E,E,E,61,40,E,E,41,42},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
		{N,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E},
};

#endif /* PRODUCTION_H_ */
